#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R "$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a error_page 404 /error404.html;' /etc/nginx/sites-available/default

sudo service nginx restart

sudo service nginx reload