#!/usr/bin/env bash
# Configure Nginx web-02

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R $USER /var/www/
echo "Hello World!" >/var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
