#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 100.

j=1
while [ $j -le 100 ]
do
    if [[ $((j % 5)) -eq 0 && $((j % 3)) -eq 0 ]]
    then
	echo "FizzBuzz"
    elif [[ $((j % 3)) -eq 0 ]]
    then
	echo "Fizz"
    elif [[ $((j % 5)) -eq 0 ]]
    then
	echo "Buzz"
    else
	echo "$j"
    fi
    j=$((j + 1))
done
