#!/usr/bin/env bash
# displays a story with each line of /etc/passwd.

input="/etc/passwd"
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
    echo "The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
done < "$input"