#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
j=1
while [ $j -lt 10 ];
do
    if [ $j -eq 9 ];
    then
        echo "Hi";
    fi
        echo "Best School";
        j=$((j))
done
