#!/usr/bin/env bash
#nginx must be running as nginx use
sudo pkill apache2
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
