#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
sudo pkill apache2
sudo chown -R nginx:nginx /etc/nginx/
sudo chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
